### ISSUE TITLE
npm run start Error

### ISSUE THREAD

**Issue by gauravubnare** [oss-videochat/bitlink#6]
Hello, while running npm run start. I am getting the error below. 

Compilation error in /root/bitlink/server/src/services/RoomService.ts
[ERROR] 01:33:27 ⨯ Unable to compile TypeScript:
src/services/RoomService.ts:11:8 - error TS2307: Cannot find module '@bitlink/common'.

**Comment by jbis9051** [comment]
Hi! Are you sure you ran `lerna bootstrap` and `lerna link`?

**Comment by gauravubnare** [comment]
Hi, yes I ran both the commands as described in the readme.md file

git clone https://github.com/oss-videochat/bitlink.git`
cd bitlink
npm install
lerna bootstrap
lerna link # may hang, see note below
cd server
MEDIASOUP_LISTEN_IP=<YOUR IP ADDRESS>; npm run start

but getting the same error

Compilation error in /root/bitlink/server/src/services/RoomService.ts
[ERROR] 01:33:27 ⨯ Unable to compile TypeScript:
src/services/RoomService.ts:11:8 - error TS2307: Cannot find module '@bitlink/common'.

**Comment by jbis9051** [comment]
Ah. I think the readme is a bit screwed up. Have you also ran this in order?

```
cd common && npm run build
cd ../frontend && npm run build
cd ../server && npm run build
```

**Comment by jbis9051** [comment]
Just tested. After running the above, I didn't receive an error. Let me know if that works for you :)

**Comment by gauravubnare** [comment]
Thanks I will check!

**Comment by gauravubnare** [comment]
Hi, Thanks I got it working :+1:

**Comment by jbis9051** [comment]
Awesome! I will update the README.md.
